### ISSUE TITLE
Hiányzó ProfileData

### ISSUE THREAD

**Issue by douggutaby** [amargo/eon-mqtt#1]
Üdv,

Most lettem eon-os és nézem a megoldásodat. Működik ez még vagy változtatott az eon? Mert nekem bejelentkezés után nincs ProfileData, ahonnan pl reportid-t tudnék kiszedni.
Szóval én vagyok béna, vagy eon változtatott? Ügyfélszolgálat az API-t se értette meg, nem hogy dokumentációval kisegítene.

**Comment by douggutaby** [comment]
Megy ez csak én bénázok curl-lel.

**Comment by amargo** [comment]
Szia, elnézést, nem kaptam email-t és most láttam, de örülök, hogy működik :)

Készülőben van egy másik is: https://github.com/amargo/appdeamon-scripts
Ez már többet tud, viszont idő hiányában a dokumentációval is lassan haladok.. 
Addig is egy kis kedv csináló: https://prohardver.hu/tema/okos_otthon_smart_home/hsz_28262-28262.html
és https://prohardver.hu/tema/okos_otthon_smart_home/hsz_28206-28206.html

**Comment by douggutaby** [comment]
Köszi a választ. python-ban nem vagyok otthon, így curl-lel próbáltam, de nem sikerült az authentikáció.
Úgyhogy kidobáltam a tiédből, hogy mqtt-re rakjon és kiírattam vele a response json-t. Ezt már jq-val fel tudom dolgozni és openhabba tölteni.
Nekem igazából ennyi elég is. Így már grafanában össze tudom pakolni, hogy mennyit termelek napelemmel, mennyit tolok a szolgáltató felé, és mennyit veszek tőlük.

**Comment by amargo** [comment]
Szuper! :)

Arra figyelj (lehet csak én nem találtam meg), hogy a +A és -A én hozzáadogatom a totálokhoz napon belül így a total értékek nem ugrálni fognak, hanem azok is 15 perces bontásban lépkednek így.
