### ISSUE TITLE
MQTT elérés hiba esetén a hibaüzenet is hibára fut

### ISSUE THREAD

**Issue by ZsBT** [amargo/eon-mqtt#4]
```
    print(datetime.datetime.now(), "Error publishing to MQTT: {0}".format(str(ex)))
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'

```

**Comment by amargo** [comment]
Szia, köszönöm az észrevételt, ezt a repot már jó egy éve nem "fejlesztem", de az elkövetkező napokban próbálok időt szakítani és HA mqtt Discovery kompatibilisre rakom majd ezt is.

**Comment by ZsBT** [comment]
Az a vad ötletem támadt, hogy a lényegi részét ki kéne rakni osztályba. Így
megmaradhat a parancssori indítás, s lehetne rá közvetlen szenzort írni
HA-ba. Ezt szívesen megcsinálom, folytathatjuk külön issue-ban és/vagy
branch-ben.
Zsombor

amargo ***@***.***> ezt írta (időpont: 2022. szept. 5., Hét
23:03):

**Comment by amargo** [comment]
Szia, köszönöm a felajánlást 😊
Mindenképp érdemes lenne kiszervezni, erre van is külön artifactory-m (azure-os) ahova lehetne rakni akár csomagokat.

**Comment by ZsBT** [comment]
Elvileg a github is automatán fel tudná tolni dockerhubba...  Kezdetnek ha
gondolod, érdemes lenne elfogadni a PR-t ami jelen issue-t javítja, meg
behozza a Dockerfile-t (ez utóbbit legalább mások is jól meg tudják
köpködni...).
Aztán a forkomban jól szétcsapnám a mostani py fájlt meg létrehozok HA
custom integration entity-t.

amargo ***@***.***> ezt írta (időpont: 2022. szept. 7., Sze
9:20):

**Comment by amargo** [comment]
Elsőnek nagyon köszönök minden segítséget :) viszont válasszuk ketté.
Legyen egy külön PR a datetime hibára.

Az image gyártás pedig legyen egy másik task, ott pedig jó lenne valami hasonló mintát követni, mint pl itt is: https://github.com/amargo/zpool-mqtt/blob/main/Dockerfile

Ugyan ez igaz az MQTT Discovery-re is: https://github.com/amargo/zpool-mqtt/blob/main/app/zpool-list.py (de másik repókban is használom)

Bevallom ennek az eon-mqtt-s projeknek az appdaemon verzió óta nincs "értelme", de látom, hogy igény azért még így is akad. Viszont, ha valami reszelgetni kellene, akkor inkább az a másik verzió :) https://github.com/amargo/appdeamon-scripts

Alapjában véve ezek az adatok jelenleg erősen összefüggenek a HA Energy Monitorjával tehát a szorosabb integráció szükséges, ha már ott a szorosabb integráció és mindenképpen docker, akkor viszont add-on-t kell csinálni, de én idő hiányában ezzel nem tudok foglalkozni, appdaemon-ba nálam jó másfél éve teszi a dolgát. 
Ennek a "sima" mqtt-s verziónak az a hátránya, hogy nincs a megfelelő idősíkon, azaz utólag kell megdolgozni, ezt csinálja meg az "integrált" változat. Ha valakinek mindenképpen szükséges a sima mqtt-s verzió, akkor ezt az egészet érdemes kicsit tovább gondolni. Ha az megvan lehet belőle image, persze :)
