### ISSUE TITLE
Set MQTT Topic

### ISSUE THREAD

**Issue by lipigab** [amargo/eon-mqtt#7]
Would it be possible to set the MQTT topic in the ENV file? I got multiple EON accounts and want to streamline which read is for which account.
Thx

**Comment by amargo** [comment]
It seems this feature was left out..
I will implement it soon, thanks!

**Comment by amargo** [comment]
Now, you can use the MQTT_TOPIC environment variable as well. 
I hope this implementation is useful to you :)
